DROP TABLE IF EXISTS CUSTOMERS;

CREATE TABLE CUSTOMERS
(
    ID           VARCHAR(36) PRIMARY KEY,
    FULL_NAME    VARCHAR(200) NOT NULL,
    PHONE_NUMBER VARCHAR(20)  NOT NULL,
    ADDRESS      VARCHAR(200) NOT NULL,
    CREATED_AT   DATE         NOT NULL
);

CREATE TABLE PURCHASE_TRANSACTIONS
(
    ID           VARCHAR(36) PRIMARY KEY,
    PAYMENT_TYPE VARCHAR(20) NOT NULL,
    AMOUNT       DECIMAL(19, 4),
    CUSTOMER_ID  VARCHAR(36),
    CREATED_AT   DATE        NOT NULL,
    FOREIGN KEY (CUSTOMER_ID) REFERENCES CUSTOMERS (ID)
)